name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    needs: other-tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: sudo apt-get install docker-compose

    - name: Build and Spin up Docker Compose
      run: docker-compose up -d --build

    - name: Print Backend Logs (for debugging)
      run: docker logs dockerized_backend

    - name: Wait for services to be ready
      run: |
        # Wait for MySQL to be ready
        until docker exec dockerized_mysql mysqladmin ping --silent; do
          echo "Waiting for MySQL...";
          sleep 3;
        done

        # Wait for Backend to be ready
        until curl -s http://localhost:8080/actuator/health | grep 'UP'; do
          echo "Waiting for Backend...";
          sleep 3;
        done

    - name: Test Backend Connectivity (for debugging)
      run: docker exec dockerized_backend curl -s http://localhost:8080/actuator/health

    - name: Run Health Checks
      run: |
        curl --fail http://localhost || exit 1

    - name: Rollback if Health Checks Fail
      if: failure()
      run: |
        echo "Health check failed, rolling back to the previous version"
        docker-compose down
        docker-compose -f docker-compose.previous.yml up -d  # Replace with your rollback command
